name: CI

on:
  - push
  - pull_request

jobs:
  test-cram:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Login shell is required to include changes by conda init bash.
        shell: bash -l -eo pipefail {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.9"
        miniforge-variant: Mambaforge
        channels: conda-forge,bioconda

    - name: Install Cram
      run: python3 -m pip install cram

    - name: Install pandas and tsv-utils
      run: mamba install "pandas>=1.0.0" "tsv-utils" "pango_aliasor>=0.3.0"

    - name: Run Cram tests
      run: cram --shell=/bin/bash tests/
