name: Run models

on:
  repository_dispatch:
    types:
      - run-models
  workflow_dispatch:
    inputs:
      slack_channel:
        description: 'Slack channel to push update alerts. Default channel is nextstrain-counts-updates.'
        required: false
      trial_name:
        description: 'Short name for a trial run that does not send Slack notifications. WARNING: without this we will overwrite files in s3://nextstrain-data/files/workflows/forecasts-ncov'
        required: false
      data_provenance:
        description: 'Data provenance of data inputs for model: gisaid or open. Will run both if left empty.'
        required: false

jobs:
  run_models:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nextstrain/.github/actions/setup-nextstrain-cli@master
      with:
        cli-version: ">=7.1.0"

    - name: install-pyyaml
      run: python3 -m pip install pyyaml

    - name: run_pipeline
      run: |
        # Need to edit the optional file with a script because we need to edit nested values
        if [[ "$TRIAL_NAME" ]]; then
          ./bin/set-trial-optional-config \
            --config-yaml config/optional.yaml \
            --s3-trial-prefix "$TRIAL_NAME" > optional.yaml
        else
          cat config/optional.yaml > optional.yaml
        fi

        declare -a override_config
        if [[ "$DATA_PROVENANCE" ]]; then
          override_config=(--config data_provenances="$DATA_PROVENANCE")
        fi

        nextstrain build \
          --aws-batch \
          --detach \
          --no-download \
          --image nextstrain/base:build-20230720T001758Z \
          --cpus 8 \
          --memory 16GiB \
          --env AWS_DEFAULT_REGION \
          --env AWS_ACCESS_KEY_ID \
          --env AWS_SECRET_ACCESS_KEY \
          --env GITHUB_RUN_ID \
          --env SLACK_TOKEN \
          --env SLACK_CHANNELS \
          . \
            --configfile config/config.yaml optional.yaml \
            --keep-going \
            "${override_config[@]}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        DATA_PROVENANCE: ${{ github.event.inputs.data_provenance || github.event.client_payload.data_provenance }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNELS: ${{ github.event.inputs.slack_channel || vars.SLACK_CHANNELS }}
        TRIAL_NAME: ${{ github.event.inputs.trial_name }}
